update php.ini
PrestaShop/docker pull request #282
Opened 2021-11-15 14:21 UTC by PrestaSafe

Avoid Error 500 `PHP Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes)`

With all templates.

2021-11-15 14:43 UTC, PierreRambaud requested changes
Afaik, without any good reason, it's not a good idea to boost docker images for your own usage.
The requirement is 256M to run PrestaShop: https://devdocs.prestashop.com/8/basics/installation/system-requirements/#system-requirements-for-prestashop-8
If it failed because you add a lot of products, themes, or modules, you're able to extend the docker image to create your own. Otherwise, maybe the php.ini file can be extended.

2021-11-15 14:48 UTC, PrestaSafe commented
It's actually a brand new prestashop 1.7.8.0, with no more products than demo products. 
I've never add this issue before this version. 
I've juste install one of my template who has 4 modules. 
It's works perfectly with all other versions.

2021-11-15 14:56 UTC, jf-viguier commented
memory_limit to 256M is not enaugh for a real world prestashop instance, why no considering that docker is mainly for dev and should be greater here ?

2021-11-15 17:15 UTC, PierreRambaud commented
If the requirements needs to be updated, it has to be done in the documentation first.
The current docker image is not designed for dev or production, it's designed for CI only, which is the reason why nothing in PHP is configurable.
And if people want to change something related to apache or PHP you can do it by overriding the docker image

2021-11-15 17:56 UTC, jf-viguier commented
Ok, thanks for the explanation.

2021-12-28 13:39 UTC, PierreRambaud commented
I'm closing it as we will not merge it like that

2021-12-28 13:39 UTC, closed without merging