Add docker files for PS 1.7.8.5
PrestaShop/docker pull request #302
Opened 2022-03-17 16:25 UTC by matthieu-rolland

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add docker files for prestashop 1.7.8.5
| Type?             | Improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27862
| How to test?      | 
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

2022-03-17 16:26 UTC, Progi1984 approved these changes

2022-03-17 16:26 UTC, PierreRambaud approved these changes

2022-03-17 16:27 UTC, PierreRambaud requested changes
Wait for the release :)

2022-03-18 11:34 UTC, jolelievre approved these changes

2022-03-18 11:34 UTC, merged