Images for 8.0.0-beta.1
PrestaShop/docker pull request #313
Opened 2022-08-22 15:55 UTC by jolelievre

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| How to test?      | ~
| Possible impacts? | ~

2022-08-22 16:37 UTC, yanmakouf approved these changes

2022-08-22 19:00 UTC, okom3pom reviewed
_https://www.prestashop.com/download/old/prestashop_8.0.0-beta.1.zip_

404 for me

2022-08-23 17:22 UTC, okom3pom approved these changes

2022-08-23 17:47 UTC, atomiix requested changes

2022-08-23 17:47 UTC, atomiix commented on images/8.0.0-beta.1/7.2-apache/Dockerfile
> +ADD https://www.prestashop.com/download/old/prestashop_8.0.0-beta.1.zip /tmp/prestashop.zip
The link is not the good one 😕

2022-08-24 08:25 UTC, atomiix approved these changes

2022-08-24 08:40 UTC, okom3pom commented
oh i just check https://github.com/PrestaShop/docker/commit/6f55564031f5e6524ba50122fc74134c3268a48b after my comment; sorry for my bad approve.

2022-08-24 09:12 UTC, merged

2022-08-29 09:29 UTC, hugofintecture commented
Hello! Does this can be tested now? I don't see the new builds on Docker Hub https://hub.docker.com/r/prestashop/prestashop/tags?page=1&ordering=last_updated
Thanks in advance :)

2022-08-30 08:20 UTC, atomiix commented
@hugofintecture it should be good now! https://hub.docker.com/layers/prestashop/prestashop/prestashop/8.0.0-beta.1/images/sha256-777ac9be3cbc8bcb2a3dc19d1176dce074e13aab7ab2d358a5c77236024aaaf4?context=explore

2022-08-30 08:25 UTC, hugofintecture commented
Thank you for your reactivity! I'll try it :)